############################################################################
# apps/examples/w25fs/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

# W25Q64 Flash filesystem demo application info

PROGNAME  = w25fs
PRIORITY  = 100
STACKSIZE = 2048
MODULE    = $(CONFIG_EXAMPLES_W25FS)

MAINSRC = w25fs_main.c

include $(APPDIR)/Application.mk
