############################################################################
# Contest 2026 - Image Display App Makefile
# Team: 金色传说 (Team #319)
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = image_display
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_CONTEST2026_IMAGE_DISPLAY)

MAINSRC = image_display_main.c

include $(APPDIR)/Application.mk
