############################################################################
# Contest 2026 - Screen Test App Makefile
# Team: 金色传说 (Team #319)
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = screen_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_CONTEST2026_SCREEN_TEST)

MAINSRC = screen_test_main.c

include $(APPDIR)/Application.mk
