############################################################################
# apps/examples/imu/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = imu
PRIORITY  = 100
STACKSIZE = 2048
MODULE    = $(CONFIG_EXAMPLES_IMU)

MAINSRC = imu_main.c

include $(APPDIR)/Application.mk
